# Generated by Django 5.1.1 on 2024-11-30 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_remove_venta_metodo_pago_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='es_pago_parcial',
            field=models.BooleanField(default=False),
        ),
    ]
