# Generated by Django 5.1.1 on 2024-12-02 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0005_alter_detalleventa_producto_alter_venta_usuario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venta',
            options={'ordering': ['-create_at']},
        ),
    ]
