# Generated by Django 5.1.1 on 2024-12-03 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0007_promocion_producto_promocion'),
        ('ventas', '0006_alter_venta_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleventa',
            name='descuento_aplicado',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='promocion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='productos.promocion'),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='subtotal',
            field=models.PositiveIntegerField(),
        ),
    ]
