# Generated by Django 5.1.1 on 2024-11-21 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='categoria',
            table=None,
        ),
    ]
