# Generated by Django 5.1.1 on 2024-11-23 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_alter_categoria_nombre_alter_marca_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
