# Generated by Django 5.1.1 on 2024-11-09 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0010_remove_producto_id_alter_producto_codigo_qr_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='created',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='updated_at',
        ),
        migrations.CreateModel(
            name='FechaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_elaboracion', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fechas', to='productos.producto')),
            ],
            options={
                'db_table': 'fecha_producto',
            },
        ),
    ]
