# Generated by Django 5.1.1 on 2024-11-09 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0011_remove_producto_created_remove_producto_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='codigo_qr',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
