# Generated by Django 5.1.1 on 2024-10-06 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitor',
            old_name='SessionKey',
            new_name='session_key',
        ),
        migrations.RenameField(
            model_name='visitor',
            old_name='TargetUser',
            new_name='target_user',
        ),
    ]
