# Generated by Django 5.1.1 on 2024-10-08 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='codigo_qr',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
