# Generated by Django 5.1.1 on 2024-10-08 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_alter_producto_precio_alter_producto_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(default='placeholder.png', upload_to='productosImage/'),
        ),
    ]
