# Generated by Django 5.1.1 on 2024-10-09 03:13

import django.db.models.constraints
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_producto_autor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='producto',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['DEFERRED'], fields=('codigo_qr',), name='unique_codigo_qr'),
        ),
        migrations.AlterModelTable(
            name='producto',
            table=None,
        ),
    ]
